add-saving-apartment-entry-date-and-neighborhood-to-firebase
amit-schwartz-u/rooMe pull request #119
Opened 2020-05-19 13:03 UTC by amit-schwartz-u

add-saving-apartment-entry-date-and-neighborhood-to-firebase

2020-05-19 20:41 UTC, ShaharBirzon approved these changes
אחלה!

2020-05-20 14:48 UTC, levYuval1007 requested changes
good work!

2020-05-20 14:48 UTC, levYuval1007 commented on app/src/main/java/com/example/roome/Roommate_searcher_tabs_classes/EditProfileRoommateSearcher.java
> +        validateUserInput();
why moved from onActivityCreatd?

2020-05-20 14:48 UTC, levYuval1007 commented on app/src/main/java/com/example/roome/Roommate_searcher_tabs_classes/EditProfileRoommateSearcher.java
> +        chosenDate = getView().findViewById(R.id.tv_show_here_entry_date);
great!

2020-05-20 16:49 UTC, merged